"""Autonomous Self-Healing Execution Engine & Learned Experience Cache for J.A.R.V.I.S.
Intercepts failed commands, applies multi-tier heuristics & LLM code generation,
executes the repair, and commits working solutions to persistent memory.
"""
import os
import re
import json
import time
import difflib
import subprocess
import shlex
import requests

# Approved binaries for self-healing repair execution (shell=False only)
SAFE_BASH_BINARIES = {
    "open", "pkill", "defaults", "afplay", "pmset", "killall",
    "screencapture", "say"
}

DANGEROUS_SHELL_PATTERNS = re.compile(
    r"[;&|`$><]|(?:\b(?:rm|dd|mkfs|chmod|chown|sudo|curl|wget|nc|bash|sh|zsh|eval|exec|python|perl|ruby)\b)",
    re.I
)


def is_safe_command(cmd_type: str, cmd: str) -> tuple[bool, str, list[str] | None]:
    """Strictly validates commands generated by self-healing to prevent arbitrary code execution."""
    if not cmd or not isinstance(cmd, str):
        return False, "Empty or invalid command format", None

    clean_cmd = cmd.strip()

    if cmd_type == "applescript":
        # Disallow arbitrary shell execution via AppleScript escape hatch
        if "do shell script" in clean_cmd.lower():
            return False, "AppleScript containing 'do shell script' is forbidden for security", None
        return True, "OK", ["osascript", "-e", clean_cmd]

    elif cmd_type == "bash":
        # Block dangerous shell operators and commands
        if DANGEROUS_SHELL_PATTERNS.search(clean_cmd):
            return False, f"Command contains forbidden shell metacharacters or dangerous binaries: {clean_cmd}", None

        try:
            tokens = shlex.split(clean_cmd)
        except Exception as e:
            return False, f"Command cannot be safely parsed: {e}", None

        if not tokens:
            return False, "No executable tokens found", None

        binary = os.path.basename(tokens[0]).lower()
        if binary not in SAFE_BASH_BINARIES:
            return False, f"Binary '{binary}' is not in approved safe binaries whitelist", None

        return True, "OK", tokens

    return False, f"Unsupported command type '{cmd_type}'", None

LEARNED_STORE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "learned_actions.json")
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen3:1.7b")
NVIDIA_KEY = os.getenv("NVIDIA_API_KEY", "")


class LearnedActionStore:
    """Episodic memory store for dynamically healed actions."""
    def __init__(self, filepath=LEARNED_STORE_PATH):
        self.filepath = filepath
        self.rules = {}
        self.load()

    def load(self):
        if os.path.exists(self.filepath):
            try:
                with open(self.filepath, "r", encoding="utf-8") as f:
                    self.rules = json.load(f)
            except Exception as e:
                print(f"  [LearnedStore] Error reading store: {e}")
                self.rules = {}
        else:
            self.rules = {}

    def save(self):
        try:
            with open(self.filepath, "w", encoding="utf-8") as f:
                json.dump(self.rules, f, indent=2)
        except Exception as e:
            print(f"  [LearnedStore] Error writing store: {e}")

    def normalize(self, query: str) -> str:
        q = query.lower().strip(" .!?,;\"'")
        q = re.sub(r'^(?:(?:hey|hi|hello|ok|okay)?\s*(?:jarvis|siri|friday|jev)[,\s]*)+', '', q).strip()
        q = re.sub(r'^(?:please|could you|can you)\s+', '', q).strip()
        return q

    def get(self, query: str):
        clean = self.normalize(query)
        if clean in self.rules:
            return self.rules[clean]
        # Check fuzzy match
        for stored_query, entry in self.rules.items():
            ratio = difflib.SequenceMatcher(None, clean, stored_query).ratio()
            if ratio >= 0.88:
                return entry
        return None

    def learn(self, query: str, action_type: str, payload: dict, spoken_reply: str):
        clean = self.normalize(query)
        if not clean:
            return
        self.rules[clean] = {
            "type": action_type,
            "payload": payload,
            "reply": spoken_reply,
            "learned_at": time.time(),
            "hit_count": 1
        }
        self.save()
        print(f"  [Self-Healing] Committed new learned rule for: '{clean}' -> {action_type}")


_STORE = LearnedActionStore()


def get_learned_store() -> LearnedActionStore:
    return _STORE


# ---------------------------------------------------------------------------
# Self-Healing Heuristics
# ---------------------------------------------------------------------------

def heal_app_name(raw_name: str) -> str | None:
    """Fuzzy scan macOS application directories when exact Spotlight match misses."""
    clean = raw_name.lower().strip()
    # Common user nicknames
    nicknames = {
        "vs code": "Visual Studio Code",
        "vscode": "Visual Studio Code",
        "code": "Visual Studio Code",
        "terminal": "Terminal",
        "term": "Terminal",
        "brave": "Brave Browser",
        "chrome": "Google Chrome",
        "edge": "Microsoft Edge",
        "calc": "Calculator",
        "word": "Microsoft Word",
        "excel": "Microsoft Excel",
        "ppt": "Microsoft PowerPoint",
        "powerpoint": "Microsoft PowerPoint",
        "music": "Music",
        "spotify": "Spotify",
        "messages": "Messages",
        "mail": "Mail",
        "slack": "Slack",
        "notes": "Notes",
        "reminders": "Reminders",
    }
    if clean in nicknames:
        return nicknames[clean]

    # Search application folders
    app_dirs = ["/Applications", "/System/Applications", os.path.expanduser("~/Applications")]
    candidates = []
    for d in app_dirs:
        if os.path.exists(d):
            for item in os.listdir(d):
                if item.endswith(".app"):
                    candidates.append(item[:-4])

    # Find best fuzzy match
    matches = difflib.get_close_matches(clean, candidates, n=1, cutoff=0.6)
    if matches:
        return matches[0]

    return None


def execute_learned_entry(entry: dict) -> str:
    """Execute a previously healed action from the learned store."""
    atype = entry.get("type")
    payload = entry.get("payload", {})
    reply = entry.get("reply", "Done, sir.")

    if atype == "applescript":
        script = payload.get("script", "")
        subprocess.run(["osascript", "-e", script], capture_output=True, text=True)
        return reply

    if atype == "bash":
        cmd = payload.get("cmd", "")
        subprocess.run(cmd, shell=True, capture_output=True, text=True)
        return reply

    if atype == "open_app":
        app_name = payload.get("app_name", "")
        subprocess.run(["open", "-a", app_name])
        return reply

    if atype == "open_url":
        url = payload.get("url", "")
        subprocess.run(["open", url])
        return reply

    return reply


def query_llm_for_repair(user_query: str, failed_error: str) -> dict | None:
    """Use fast local LLM (or NVIDIA NIM) to generate a dynamic AppleScript/Bash self-healing fix."""
    front_app = "Desktop"
    try:
        front_app = subprocess.check_output(
            ["osascript", "-e", 'tell application "System Events" to name of first application process whose frontmost is true'],
            stderr=subprocess.DEVNULL, text=True
        ).strip()
    except Exception:
        pass

    prompt = f"""You are an autonomous macOS self-healing operating system controller.
A user voice command failed to execute.
User command: "{user_query}"
Current active macOS app: "{front_app}"
Error / Failure reason: "{failed_error}"

Generate an exact, robust AppleScript or Bash command that successfully accomplishes what the user wants on macOS.
Output a JSON object ONLY with no markdown or formatting outside JSON:
{{
  "type": "applescript" or "bash",
  "command": "the exact script to run",
  "confirmation": "1 short natural spoken sentence confirming the action as J.A.R.V.I.S."
}}
"""

    # 1. Try Local Ollama (sub-second)
    try:
        r = requests.post(
            f"{OLLAMA_HOST}/v1/chat/completions",
            json={
                "model": OLLAMA_MODEL,
                "messages": [
                    {"role": "system", "content": "You output valid JSON only."},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.0,
                "max_tokens": 200
            },
            timeout=8
        )
        if r.status_code == 200:
            content = r.json()["choices"][0]["message"]["content"].strip()
            content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
            m = re.search(r"\{.*\}", content, re.DOTALL)
            if m:
                return json.loads(m.group(0))
    except Exception as e:
        print(f"  [Self-Healing Local LLM] {e}")

    # 2. Try NVIDIA NIM Fallback
    if NVIDIA_KEY:
        try:
            r = requests.post(
                "https://integrate.api.nvidia.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {NVIDIA_KEY}"},
                json={
                    "model": "meta/llama-3.2-3b-instruct",
                    "messages": [
                        {"role": "system", "content": "Output valid JSON only."},
                        {"role": "user", "content": prompt}
                    ],
                    "temperature": 0.1,
                    "max_tokens": 200
                },
                timeout=10
            )
            if r.status_code == 200:
                content = r.json()["choices"][0]["message"]["content"].strip()
                m = re.search(r"\{.*\}", content, re.DOTALL)
                if m:
                    return json.loads(m.group(0))
        except Exception as e:
            print(f"  [Self-Healing NVIDIA NIM] {e}")

    return None


def self_heal_action(task_text: str, failed_reply: str, original_executor) -> str | None:
    """Apply self-healing remediation when an action fails or returns an unconfident reply."""
    print(f"\n  [Self-Healing Triggered] for: '{task_text}' (Previous error: {failed_reply})")

    # Heuristic 1: App launch failure ("I couldn't locate an application...")
    m_open = re.search(r'^(?:open|launch|start|run|switch\s+to|bring\s+up)\s+(.+)$', task_text, re.I)
    if m_open:
        target = m_open.group(1).strip(" .!?")
        healed_app = heal_app_name(target)
        if healed_app:
            try:
                res = subprocess.run(["open", "-a", healed_app], capture_output=True, text=True)
                if res.returncode == 0:
                    reply = f"Opening {healed_app}, sir."
                    _STORE.learn(task_text, "open_app", {"app_name": healed_app}, reply)
                    return reply
            except Exception:
                pass

        # Check web app resolution
        web_clean = target.lower().replace(" ", "")
        url = f"https://www.{web_clean}.com"
        subprocess.run(["open", url])
        reply = f"Opening {target.title()} in your browser, sir."
        _STORE.learn(task_text, "open_url", {"url": url}, reply)
        return reply

    # Heuristic 2: GUI or Web Click failure
    if re.search(r"\b(?:click|link|button)\b", task_text, re.I):
        # Fall back to native macOS Accessibility keystrokes or UI element scripting
        applescript = """
        tell application "System Events"
            key code 36 using {} -- Return key
        end tell
        """
        subprocess.run(["osascript", "-e", applescript])
        reply = "Triggered primary element selection, sir."
        _STORE.learn(task_text, "applescript", {"script": applescript}, reply)
        return reply

    # Heuristic 3: Autonomous LLM Script Generation & Dynamic Execution
    plan = query_llm_for_repair(task_text, failed_reply)
    if plan and "type" in plan and "command" in plan:
        cmd_type = plan["type"]
        cmd = plan["command"]
        conf = plan.get("confirmation", "Done, sir.")

        success = False
        is_safe, reason, args = is_safe_command(cmd_type, cmd)
        if not is_safe:
            print(f"  [Self-Healing Security Blocked] {reason} (Command: '{cmd}')")
            return None

        try:
            res = subprocess.run(args, capture_output=True, text=True, timeout=5)
            success = (res.returncode == 0)
        except Exception as e:
            print(f"  [Self-Healing Execution Failed] {e}")
            success = False

        if success:
            print(f"  [Self-Healing Success] Executed validated {cmd_type} repair: {cmd}")
            _STORE.learn(task_text, cmd_type, {"script" if cmd_type == "applescript" else "cmd": cmd}, conf)
            return conf

    return None
